ALTER TABLE CIUDADANO DROP FOREIGN KEY FK_CIUDADANO_DIRECCION_ID
ALTER TABLE DIRECCION DROP FOREIGN KEY FK_DIRECCION_PAIS_ID
ALTER TABLE DIRECCION DROP FOREIGN KEY FK_DIRECCION_CIUDAD_ID
ALTER TABLE DIRECCION DROP FOREIGN KEY FK_DIRECCION_SECTOR_ID
ALTER TABLE TELEFONO DROP FOREIGN KEY FK_TELEFONO_CIUDADANO_ID
ALTER TABLE CIUDADANO_TELEFONO DROP FOREIGN KEY FK_CIUDADANO_TELEFONO_Ciudadano_ID
ALTER TABLE CIUDADANO_TELEFONO DROP FOREIGN KEY FK_CIUDADANO_TELEFONO_telefonos_ID
DROP TABLE CIUDADANO
DROP TABLE DIRECCION
DROP TABLE TELEFONO
DROP TABLE PAIS
DROP TABLE SECTOR
DROP TABLE CIUDAD
DROP TABLE CIUDADANO_TELEFONO
